[package]
name = "target-docs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob-match = "0.2.1"
serde = { version = "1.0.196", features = ["derive"] }
toml = "0.8.10"
